### PR TITLE
updated the name of the data fields

### PR DESCRIPTION
**Pull request by ZARYABZEE**
Almost all of the data fields names has been changed

### CODE REVIEW

**Review by AhmerRowjani — APPROVED** [review]
Perfect

**Review by AhmerRowjani — APPROVED** [review]

**Review by AhmerRowjani — APPROVED** [review]

**Review by AhmerRowjani — APPROVED** [review]

**Review by AhmerRowjani — APPROVED** [review]

**Review by AhmerRowjani — APPROVED** [review]
Thanks

**Comment by AhmerRowjani** [comment]
Thanks

**Comment by ZARYABZEE** [comment]
Ahmer reviewd The 9 commits and its good to go.thanks Zaryab

**Pull request merged**
